### ISSUE TITLE
Which version of Stable Diffusion model should be used?

### ISSUE THREAD

**Issue by Georgefwt** [facebookresearch/stable_signature#1]
First of all, great work! But I'm a little confused about [this](https://github.com/facebookresearch/stable_signature#stable-diffusion-models) part in README, as you mentioned code is written for LDM and also works for SDv1, but the decoder you provided seems to be for SDv2.1.

So which version of the Stable Diffusion model should I use if I want to generate images with the decoder and extract messages?

**Comment by pierrefdz** [comment]
Hi, thanks for your message.

The decoder is almost the same between SDv1 and SDv2. They fine-tuned it after v1 to improve generation of small details like text - if I am not mistaken. Therefore the decoder weights can be used for both models (and all the original LDMs since they use the same decoder, except for the upscaling ones).

However, I know that the codebase and the loading of the weights is done differently between https://github.com/Stability-AI/stablediffusion/ (v2) and https://github.com/CompVis/stable-diffusion (v1). 
What is said in the readme file: https://github.com/facebookresearch/stable_signature#generate is specific for the Stability-AI codebase. You might need to load the weights different if you want to plug this on previous generation scripts.

**Comment by Georgefwt** [comment]
Thanks for your quick reply. I will try it as soon as possible!

**Comment by Georgefwt** [comment]
Thank you, I managed to get it working. There seems to be something slightly inaccurate in the README: the decoder you provided appears to already be the state dict, so `torch.load(path/to/ldm/checkpoint_000.pth)['ldm_decoder']` should remove `['ldm_decoder']` while I'm testing.

**Comment by pierrefdz** [comment]
Thanks, I have updated the readme to include this info.
