### ISSUE TITLE
Hello from the diffusers team :)

### ISSUE THREAD

**Issue by sayakpaul** [facebookresearch/stable_signature#16]
Hello there. I am Sayak, one of the maintainers of Diffusers. 

Thank you so much for also providing an example usage with Diffusers. 

I wanted to know if there is any plan to support SDXL watermarker as well? I think that will be very beneficial for the community. 

Additionally, if there is some end-to-end guidance / example of how Stable Signature performs on fine-tuned models, that would he great!

**Comment by pierrefdz** [comment]
> I wanted to know if there is any plan to support SDXL watermarker as well? I think that will be very beneficial for the community.

Hi Sayak, thank you for your interest in the project 🙂
I don't currently plan to support other models. There is an example for here [SDXL turbo](https://huggingface.co/spaces/imatag/stable-signature-bzh)

> Additionally, if there is some end-to-end guidance / example of how Stable Signature performs on fine-tuned models, that would he great!

The paper reports results (Tab. 8) when fine-tuning the VAE. When the fine-tuning happens in the diffusion model (dreambooth, control-net, consistory, dream-tuner, etc.), there is no impact to the WM since they don't change the image LDM decoder.

**Comment by sayakpaul** [comment]
Alright. That helps.
