### ISSUE TITLE
Question aboud watermask model .pt file

### ISSUE THREAD

**Issue by xiaofeinot** [facebookresearch/stable_signature#19]
Hi, thanks for your work!
(1) I notice that in "README.md", Line 50, the link to "other_dec_48b_whit.torchscript.pt" is wrong. In fact, it leads to the "dec_48b_whit.torchscript.pt" now, instead of "other_dec_48b_whit.torchscript.pt". Please check that.
(2) Following the download website format of "dec_48b_whit.torchscript.pt", I try to download from "https://dl.fbaipublicfiles.com/ssl_watermarking/other_dec_48b_whit.torchscript.pt". When run "run_evals.py" using this pt file, I get a low bit_acc even in none attack mode, lower than 0.5. It would be great if you could check with that, the result seems ok when I run "run_evals.py" using "dec_48b_whit.torchscript.pt". So I think there may be wrong with "other_dec_48b_whit.torchscript.pt".

**Comment by pierrefdz** [comment]
1) Thanks for flagging this! I've just changed the readme.md in consequence.
2) Are you generating images with the same fine-tuned LDM decoder as before? Since the watermark extractor changes, it does not match the watermark embedded in images generated by the LDM decoder fine-tuned for "dec_48b_whit". Otherwise could you be more precise on your expe such that I could find where there may be an issue?

**Comment by pierrefdz** [comment]
Hi again!
Indeed, the "sd2_decoder.pth" is specific to the "dec_xxx.pt".
You can see the system figure in the paper that explains the method. The idea is to fine-tune the sd decoder such that generated images hide a message for a given watermark extractor.
If you want to test for "other_dec_xxx" you will need to re-fine-tune the SD decoder specifically for this watermark extractor.
